urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from .views import popup_closer

app_name = "touglates"

urlpatterns = [
    path(
        "popup_closer/<int:pk>/<str:model_name>/<str:app_name>/",
        popup_closer,
        name="popup_closer",
    ),
    # to use the following path, there must be values for all three of to_field_value, attrs, and callback
    # to_field_value: The ID field.  If "-" then pk will be used
    # attrs: Extra attrs to be included in the new select option
    # callback: A javascript function to be called after the new select option is added
    # For dummy values, you can use dashes ex:
    #           return reverse("touglates:popup_closer",
    #                 kwargs={
    #                     "pk": self.object.pk,
    #                     "model_name": self.model.__name__,
    #                     "app_name": self.model._meta.app_label,
    #                     "to_field_value":"-",
    #                     "attrs":"category=" + self.object.category,
    #                     "callback": "setStyleByCategory"
    #                 },
    #             )
    path(
        "popup_closer/<int:pk>/<str:model_name>/<str:app_name>/<str:to_field_value>/<str:attrs>/<str:callback>/",
        popup_closer,
        name="popup_closer",
    ),

    path("jsi18n", JavaScriptCatalog.as_view(), name="js-catlog"),
]

forms.py
from django.forms import BoundField


class BoundFieldWithAttrs(BoundField):
    def __init__(self, form, field, name, attrs):
        super().__init__(form, field, name)
        self.attrs = attrs

    def build_widget_attrs(self, attrs, widget=None):
        built_attrs = super().build_widget_attrs(attrs, widget)
        built_attrs.update(self.attrs)
        return built_attrs

views.py
from django.apps import apps
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.html import escape
import urllib

def popup_closer(request, app_name, model_name, pk, to_field_value="-", attrs="-", callback="-"):
    object = apps.get_model(app_name, model_name).objects.get(pk=pk)
    label = escape(str(object))
    nothings=["-","_",""]
    value = pk if to_field_value in nothings else urllib.parse.unquote_plus(to_field_value)
    if to_field_value in nothings:
        to_field_value = ""
    if attrs in nothings:
        attrs = ""
    if callback in nothings:
        callback = ""

    callbackcall=""
    if callback > "":
        callbackcall = f"""window.opener.{ callback }()"""

    response_text = f"""
    <script>
        window.opener.addOptionFromRelatedPopup("{value}","{label}","{model_name}","{app_name}", "{ attrs }")
        { callbackcall }
        window.close()
    </script>
    """

    return HttpResponse(response_text)

def make_labels(model):
    labels = {
        field.name: field.verbose_name.title()
        for field in model._meta.get_fields()
        if type(field).__name__[-3:] != "Rel"
    }

    return labels

templates/touglates/base.html
{% load static %}
{% load touglates_tags %}
<!DOCTYPE HTML>
<html>
  {% block head %}
    <head>
      {% block head_meta %}
        {% if object %}
          {% if object.title %}
            <meta property="og:title" content="{{ object.title|safe  }}" />
          {% elif object.headline %}
              <meta property="og:title" content="{{ object.headline|safe  }}" />
          {% elif object.name %}
            <meta property="og:title" content="{{ object.name|safe  }}" />
          {% endif %}
          {% if object.featured_image %}
            <meta property="og:image" content="{{ object.featured_image.url  }}" />
            <meta property="og:image:alt" content="{{ object.featured_image.alt_text  }}" />
            <meta property="og:description" content="{{ object.summary }}" />
          {% endif %}
        {% endif %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% endblock %}
      {% block head_title %}
        <title>
          {% if touglates.SITE_NAME %}{{ touglates.SITE_NAME }}{% else %}{{ touglates.SITE_TITLE }}{% endif %}{% if object.title %} : {{ object.title|safe  }}{% elif object.headline %} : {{ object.headline|safe  }}{% elif object.name %} : {{ object.name|safe }}{% endif %}
        </title>
      {% endblock %}
      {% block head_stylesheet %}
        <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
        <link rel="stylesheet" href="{% static 'touglates/touglates.css' %}">

        {% for stylesheet in touglates.STYLESHEETS %}
          <link rel="stylesheet" href="{% static stylesheet %}">
        {% endfor %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Gilda+Display&display=swap" rel="stylesheet">
      {% endblock %}
      {% block head_script %}
        <script src="{% static 'touglates/touglates.js' %}"></script>
      {% endblock %}
      {% comment %}The next lines allow use of admin widgets{% endcomment %}
      <script src="{% url 'touglates:js-catlog' %}"></script>
      <script src="{% static '/admin/js/core.js' %}"></script>
      {% block head_extra %}
      {% endblock %}
    </head>
  {% endblock %}
  {% block body %}

  {% endblock %}
</html>

templates/touglates/clearable_text.html
{% load static %}
{% include "django/forms/widgets/input.html" %}
<button id="clear_{{ widget.attrs.id }}" type="button"><img src="{% static 'touglates/clear_icon.ico' %}" style="height:.8em;" title="clear" alt="clear"></button>

<script>

  var input_{{ widget.attrs.id }} = document.getElementById("{{ widget.attrs.id }}")
  var clear_{{ widget.attrs.id }} = document.getElementById("clear_{{ widget.attrs.id }}")
  clear_{{ widget.attrs.id }}.addEventListener("click", function(e) {
    e.preventDefault()
    input_{{ widget.attrs.id }}.value = ""
  })

</script>

templates/touglates/date_field.html
{% include "django/forms/widgets/date.html" %}

<script>

  widget=document.getElementById('{{ widget.attrs.id|safe }}')
  inp_duedate = document.getElementById('{{ widget.attrs.id }}')

  {% if "all" in widget.buttons or "years" in widget.buttons or "increase_year" in widget.buttons or "increases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days= "0"
    button.dataset.months= "12"
    button.classList.add("adjust-date")
    button.innerHTML = 'y>'
    inp_duedate.parentNode.insertBefore(button, inp_duedate.nextSibling )
  {% endif %}
  {% if "all" in widget.buttons or "years" in widget.buttons or "decrease_year" in widget.buttons or "decreases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "0"
    button.dataset.months = "-12"
    button.classList.add("adjust-date")
    button.innerHTML = '&lt;y'
    inp_duedate.parentNode.insertBefore(button, inp_duedate )
  {% endif %}
  
  {% if "all" in widget.buttons or "months" in widget.buttons or "increase_month" in widget.buttons or "increases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days= "0"
    button.dataset.months= "1"
    button.classList.add("adjust-date")
    button.innerHTML = 'm>'
    inp_duedate.parentNode.insertBefore(button, inp_duedate.nextSibling )
  {% endif %}
  {% if "all" in widget.buttons or "months" in widget.buttons or "decrease_month" in widget.buttons or "decreases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "0"
    button.dataset.months = "-1"
    button.classList.add("adjust-date")
    button.innerHTML = '&lt;m'
    inp_duedate.parentNode.insertBefore(button, inp_duedate )
  {% endif %}
  {% if "all" in widget.buttons or "weeks" in widget.buttons or "increase_week" in widget.buttons or "increases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "7"
    button.dataset.months = "0"
    button.classList.add("adjust-date")
    button.innerHTML = 'w>'
    inp_duedate.parentNode.insertBefore(button, inp_duedate.nextSibling )
  {% endif %}
  {% if "all" in widget.buttons or "weeks" in widget.buttons or "decrease_week" in widget.buttons or "decreases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "-7"
    button.dataset.months = "0"
    button.classList.add("adjust-date")
    button.innerHTML = '&lt;w'
    inp_duedate.parentNode.insertBefore(button, inp_duedate )
  {% endif %}
  {% if "all" in widget.buttons or "days" in widget.buttons or "increase_day" in widget.buttons or "increases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "1"
    button.dataset.months = "0"
    button.classList.add("adjust-date")
    button.innerHTML = 'd>'
    inp_duedate.parentNode.insertBefore(button, inp_duedate.nextSibling )
  {% endif %}
  {% if "all" in widget.buttons or "days" in widget.buttons or "decrease_day" in widget.buttons or "decreases" in widget.buttons %}
    button = document.createElement('button')
    button.type="button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.days = "-1"
    button.dataset.months = "0"
    button.innerHTML = '&lt;d'
    button.classList.add("adjust-date")
    inp_duedate.parentNode.insertBefore(button, inp_duedate )
  {% endif %}

  {% if "all" in widget.buttons or "today" in widget.buttons %}
    button = document.createElement('button')
    button.id = widget.id + '_button'
    button.type = "button"
    button.class="touglates_date_adjust"
    button.dataset.target = widget.id
    button.dataset.today = "true"
    button.innerText='Today'
    button.classList.add("adjust-date")
    widget.parentNode.insertBefore(button,widget.nextSibling)
  {% endif %}

  buttons = document.getElementsByClassName("adjust-date")

  for(button of buttons) {

    button.addEventListener("click", function(e){
      e.preventDefault
      if(e.target.dataset.today=="true") {
        adjustDate(e.target.dataset.target, 0, 0, true)
      } else {
        adjustDate(e.target.dataset.target, e.target.dataset.days, e.target.dataset.months)
      }
    })
  }
</script>

templates/touglates/datetime_field.html
{% include "django/forms/widgets/datetime.html" %}
<script>
    widget=document.getElementById('{{ widget.attrs.id|safe }}')
    widget.type = "datetime-local"
    button = document.createElement('button')
    button.id = widget.id + '_button'
    button.type = "button"
    button.dataset.target = widget.id
    button.innerText='Today'
    widget.parentNode.insertBefore(button,widget.nextSibling)
    button.addEventListener('click', function(e) {
      document.getElementById(e.target.dataset.target).valueAsDate = new Date()
    })
</script>

templates/touglates/dropdown_select.html
  {% load static %}
  <input id="display_{{ widget.attrs.id }}">
  <br id="br_{{ widget.attrs.id }}">
  <select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for widget in group_choices %}
    {% include widget.template_name %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>
  <button id="clear_{{ widget.attrs.id }}" type="button"><img src="{% static 'touglates/clear_icon.ico' %}" style="height:.8em;" title="clear" alt="clear"></button>

<script>

  var select_{{ widget.attrs.id }} = document.getElementById("{{ widget.attrs.id }}")
  var br_{{ widget.attrs.id }} = document.getElementById("br_{{ widget.attrs.id }}")
  var display_{{ widget.attrs.id }} = document.getElementById("display_{{ widget.attrs.id }}")
  var clear_{{ widget.attrs.id }} = document.getElementById("clear_{{ widget.attrs.id }}")
  var {{ widget.attrs.id }}_initial_display = select_{{ widget.attrs.id }}.style.display
  var br_{{ widget.attrs.id }}_initial_display = br_{{ widget.attrs.id }}.style.display

  intiateDropdown( "{{ widget.attrs.id }}" )


  updateDisplay( "{{ widget.attrs.id }}" )
  showHide( "{{ widget.attrs.id }}", "hide")



</script>

templates/touglates/form.html
{% extends './base.html' %}
{% load static %}
{% block head_script %}
  {{ block.super }}
  <script src="{% static 'touglates/formsets.js' %}"></script>
{% endblock %}

templates/touglates/form_button.html
<div class="form-field-outer-wrapper">

  <div class="form-field-inner-wrapper">
    <div class="form-field-label">
      {% if label %}
        {{ label }}
      {% endif %}
    </div>
    <div class="form-field-control">
      {{ before_button }}
      {{ button }}
      {{ after_button }}
    </div>
    {% if help_text %}
      <div class="form-field-help-text">
          {{ help_text }}
      </div>
    {% endif %}
  </div>
</div>

templates/touglates/form_field.html
<div class="form-field-outer-wrapper">
  {% if field.errors %}
    <div class="errors">
      {{ field.errors }}
    </div>
  {% endif %}
  {% if field_1.errors %}
    <div class="errors">
      {{ field_1.errors }}
    </div>
  {% endif %}
  {% if field_2.errors %}
    <div class="errors">
      {{ field_2.errors }}
    </div>
  {% endif %}
  {% if field_3.errors %}
    <div class="errors">
      {{ field_3.errors }}
    </div>
  {% endif %}
  {% if field_4.errors %}
    <div class="errors">
      {{ field_4.errors }}
    </div>
  {% endif %}
  {% if field_5.errors %}
    <div class="errors">
      {{ field_5.errors }}
    </div>
  {% endif %}
  {% if field_6.errors %}
    <div class="errors">
      {{ field_6.errors }}
    </div>
  {% endif %}

  <div class="form-field-inner-wrapper">
    <div class="form-field-label">
      {% if label_tag %}
        {{ label_tag }}
      {% else %}
        {{ field.label_tag }}
      {% endif %}
    </div>
    <div class="form-field-control">
      {{ before_field }}{{ before_fields }}
      {% if field %}
        {{ field }}
      {% elif field_1 %}
      {{ field_1_label }} {{ field_1 }}
        {% if field_2 %}
          {{ between_fields }}{{ field_2_label }}{{ field_2 }}
          {% if field_3 %}
            {{ between_fields }}{{ field_3_label }}{{ field_3 }}
            {% if field_4 %}
              {{ between_fields }}{{ field_4_label }}{{ field_4 }}
              {% if field_5 %}
                {{ between_fields }}{{ field_5_label }}{{ field_5 }}
                {% if field_6 %}
                  {{ between_fields }}{{ field_6_label }}{{ field_6 }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endif %}
      {% elif fields %}
        {% for field in fields %}
          {% if not forloop.first %}{{ between_fields }}{% endif %}{{ field }}
        {% endfor %}
      {% endif %}
      {{ after_fields }}{{ after_field }}
    </div>
    <div class="form-field-help-text">
      {% if help_text %}
        {{ help_text }}
      {% else %}
      {{ field.help_text}}
      {% endif %}
    </div>
  </div>
</div>

templates/touglates/honeypot_field.html
{% include "django/forms/widgets/input.html" %}

templates/touglates/list_field.html
{% if tag %}
<{{ tag }} class="list-field field column {{ extra_classes }}">
  {{ before_field }}
  {% if href %}
    <a href="{{ href }}" {{ href_atts }}>{{ field }}</a>
  {% else %}
    {{ field }}
  {% endif %}
  {{ after_field }}
</{{ tag }}>
{% else %}
<div class="list-field field column  {{ extra_classes }}">
  {{ before_field }}
  {% if href %}
    <a href="{{ href }}" {{ href_atts }}>{{ field }}</a>
  {% else %}
    {{ field }}
  {% endif %}
  {{ after_field }}
</div>
{% endif %}

templates/touglates/list_fields.html
{% if tag %}
<{{ tag }} class="list-field field column {{ extra_classes }}">
  {{ before_field }}{{ before_fields }}
    {{ field_1_label }} {% if href_1 %}<a href="{{ href_1 }}" {{ href_1_atts }}>{{ field_1 }}</a>{% else %}{{ field_1 }}{% endif %}
    {% if field_2 %}
      {{ between_fields }} {{ field_2_label }} {% if href_2 %}<a href="{{ href_2 }}" {{ href_2_atts }}>{{ field_2 }}</a>{% else %}{{ field_2 }}{% endif %}
    {% endif %}
    {% if field_3 %}
      {{ between_fields }} {{ field_3_label }} {% if href_3 %}<a href="{{ href_3 }}" {{ href_3_atts }}>{{ field_3 }}</a>{% else %}{{ field_3 }}{% endif %}
    {% endif %}
    {% if field_4 %}
      {{ between_fields }} {{ field_4_label }} {% if href_4 %}<a href="{{ href_4 }}" {{ href_4_atts }}>{{ field_4 }}</a>{% else %}{{ field_4 }}{% endif %}
    {% endif %}
    {% if field_5 %}
      {{ between_fields }} {{ field_5_label }} {% if href_5 %}<a href="{{ href_5 }}" {{ href_4_atts }}>{{ field_5 }}</a>{% else %}{{ field_5 }}{% endif %}
    {% endif %}
    {% if field_6 %}
      {{ between_fields }} {{ field_6_label }} {% if href_5 %}<a href="{{ href_6 }}" {{ href_6_atts }}>{{ field_6 }}</a>{% else %}{{ field_6 }}{% endif %}
    {% endif %}
  {{ after_fields }}{{ after_field }}
</{{ tag }}>
{% else %}
<div class="list-field field column  {{ extra_classes }}">
  {{ before_field }}{{ before_fields }}
    {{ field_1_label }} {% if href_1 %}<a href="{{ href_1 }}" {{ href_1_atts }}>{{ field_1 }}</a>{% else %}{{ field_1 }}{% endif %}
    {% if field_2 %}
      {{ between_fields }} {{ field_2_label }} {% if href_2 %}<a href="{{ href_2 }}" {{ href_2_atts }}>{{ field_2 }}</a>{% else %}{{ field_2 }}{% endif %}
    {% endif %}
    {% if field_3 %}
      {{ between_fields }} {{ field_3_label }} {% if href_3 %}<a href="{{ href_3 }}" {{ href_3_atts }}>{{ field_3 }}</a>{% else %}{{ field_3 }}{% endif %}
    {% endif %}
    {% if field_4 %}
      {{ between_fields }} {{ field_4_label }} {% if href_4 %}<a href="{{ href_4 }}" {{ href_4_atts }}>{{ field_4 }}</a>{% else %}{{ field_4 }}{% endif %}
    {% endif %}
    {% if field_5 %}
      {{ between_fields }} {{ field_5_label }} {% if href_5 %}<a href="{{ href_5 }}" {{ href_4_atts }}>{{ field_5 }}</a>{% else %}{{ field_5 }}{% endif %}
    {% endif %}
      {% if field_6 %}
      {{ between_fields }} {{ field_6_label }} {% if href_5 %}<a href="{{ href_6 }}" {{ href_6_atts }}>{{ field_6 }}</a>{% else %}{{ field_6 }}{% endif %}
    {% endif %}
  {{ after_fields }}{{ after_field }}
</div>
{% endif %}

templates/touglates/list_head.html
{% if tag %}
<{{ tag }} class="list-field field column {{ extra_classes }}">
  {{ before_field }}
  {% if href %}
    <a href="{{ href }}" {{ href_atts }}>{{ field }}</a>
  {% else %}
    {{ field }}
  {% endif %}
  {{ after_field }}
</{{ tag }}>
{% else %}
<div class="list-field field column {{ extra_classes }}">
  {{ before_field }}
  {% if href %}
    <a href="{{ href }}" {{ href_atts }}>{{ field }}</a>
  {% else %}
    {{ field }}
  {% endif %}
  {{ after_field }}
</div>
{% endif %}

templates/touglates/relatedselect_field.html
{% load static %}
<p class="relatedfield">
{% include "django/forms/widgets/select.html" %}

{% if not widget.hide_add %}
<script>
  addRelatedPopupLink( "{{ widget.attrs.id|safe }}", "{{ widget.related_data.app_name }}", "{{ widget.related_data.model_name }}", "{{ widget.related_data.add_url }}"{% if widget.related_data.addlabel %}, "{{ widget.related_data.addlabel }}"{% else %},"Add"{% endif %}{% if widget.related_data.addicon %},"{{ widget.related_data.addicon }}"{% else %},"{% static 'admin/img/icon-addlink.svg' %}"{% endif %}{% if widget.related_data.to_field_name %},"{{ widget.related_data.to_field_name }}"{% endif %} )
  if("{{ widget.add_filter_input }}".toLowerCase() == "true" ) {
    addFilterInput("{{ widget.attrs.id|safe }}")
  }
</script>
{% endif %}
</p>

templates/touglates/slug_field.html
{% include "django/forms/widgets/input.html" %}

<script>
  initSlugField( "{{ widget.attrs.id|safe }}", "{{ widget.slug_name }}", "{{ widget.input_name }}" )
</script>

templates/tougrelated/selectrelated.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>